### ISSUE TITLE
Weird math

### ISSUE THREAD

**Issue by sudoaza** [saveitforparts/Carryout-Radio-Telescope#1]
Why are you doing this? 

```python
			sky_data[abs(elevation-el_end),(azimuth-az_end)]=signal_strength
```
https://github.com/saveitforparts/Carryout-Radio-Telescope/blob/4f95d72945620df74f8c8e25442b5345cd2abd0d/carryout_scan.py#L159C1-L159C68

Elevation will start at el_start and end at el_end, so it will always be equal or greater to el_start. 
Just to elevation-el_start and you'll go from 0 to el_end-el_start. Then you can drop the abs and do the same for the azimuth. 

I'd also move the `np.savetxt(f"raw-data-" + timestr +".txt", sky_data)` line 161 outside the inner loop, then you'll save only once per azimuth level, filesystem write could be slow.

**Comment by saveitforparts** [comment]
I was trying to make sure the array wrote in the same direction as the
scan, and every other line I swap the azimuth to go backwards. Probably a
better way to do that.

Originally I had another output to a preview image that updated every pixel
live, so you could watch it scan. I took that out for this version. I'm not
sure I really need to save time in the inner loop, I already have a couple
time.sleep delays so I don't run faster than the motors can handle.

But yes there are probably lots of improvements, I'm bad at coding :-)

**Comment by sudoaza** [comment]
All good, I was trying to spot where the misalignment might come from and that is the only thing That I saw that could be it.
